function CL = getNMcolors

CL = [rgb('Blue'); ...
    rgb('Red'); ...
    rgb('Green'); ...
    rgb('Yellow'); ...
    rgb('Magenta'); ...
    rgb('Cyan'); ...
    rgb('LightBlue'); ...
    rgb('Orange'); ...
    rgb('LightGreen'); ...
    rgb('Moccasin'); ...
    rgb('DarkGreen');...
    rgb('DarkBlue');...
    rgb('Indigo');...
    rgb('Brown');...
    rgb('Chocolate');...
    rgb('Sienna');...
    rgb('FireBrick')];