function nk_Ensemble_config
global NM
nk_PrintLogo

act = nk_input('ENSEMBLE LEARNING PARAMETERS', 0,'m', ...
                    ['Use ensemble learning|', ...
                     'Classifiers combination strategy|', ...
                     'Ensemble learning strategy|' ...
                     'Decision mechanism|' ...
                     'Help|' ...
                     '<<< Back'],1:6,1);

switch act
    case 1
        fl = nk_input('Use ensemble learning',0,'m','yes|no',[1,0]);
        if fl 
            ENSEMBLE.flag = 1;
        else
            ENSEMBLE = [];
        end
    case 2
        ENSEMBLE.EnsTrainMode = nk_input('Single classifier training mode',0,'m', ...
            ['Use CV1 training and CV1 validation data for training|' ...
            'Use only CV1 training data for training'],[1,2],2);
        ENSEMBLE.EnsGridMode = nk_input('Combine classifiers across SVM parameters grid positions',0, ...
            'yes|no',[1,0],1);
    case 3
        ENSEMBLE.EnsStrategy = nk_input('Ensemble learning strategy',0,'m', ...
            ['Simple ''bagging-like'' combination strategy|' ...
             'Boosting strategy|' ...
             'Entropy maximization strategy|' ...
             'Pruning strategy'],1:4,1);
    case 4
        ENSEMBLE.DecisionMode = nk_input('How to decide about group membership?',0,'m', ...
            ['Maximum vote|' ...
             'Mean decision value|' ...
             'Second-layer SVM training'],1:3,1);
    case 5
    case 6
        return
end

NM.TrainParam.ENSEMBLE = ENSEMBLE;
NM = nk_Ensemble_config(NM);

return