function [res, FusionType] = nk_Fusion_config(res, varind)

if exist('varind','var') && numel(varind) > 1
    FusionType = nk_input('Select multimodal fusion strategy',0,'m', ...
            ['Early fusion -> Modality concatenation BEFORE feature preprocessing|' ...
             'Intermediate fusion -> Modality concatenation AFTER preprocessing'],1:2);
else
    FusionType = nk_input('Select multimodal fusion strategy',0,'m', ...
            ['No fusion|' ...
             'Early fusion -> Modality concatenation BEFORE feature preprocessing|' ...
             'Intermediate fusion -> Modality concatenation AFTER preprocessing|' ...
             'Late fusion -> Decision-based data fusion (bagging)'],0:3);
end

res.TrainParam.FUSION.flag = FusionType;

return